"""change name of a column

Revision ID: 1d888ebdeb46
Revises: 2b307b8088cc
Create Date: 2025-07-18 22:46:50.878604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d888ebdeb46'
down_revision: Union[str, Sequence[str], None] = '2b307b8088cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('chunks', 'chunk_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chunks', 'chunk_meatadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_meatadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('chunks', 'chunk_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('chunks', 'chunk_metadata')
    # ### end Alembic commands ###
