"""adding new col

Revision ID: 2b307b8088cc
Revises: df181aaa9f52
Create Date: 2025-07-18 21:01:47.388314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b307b8088cc'
down_revision: Union[str, Sequence[str], None] = 'df181aaa9f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'chunk_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'chunk_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
