"""adding new col

Revision ID: ecf12c5dae04
Revises: 2fe2f3c20576
Create Date: 2025-07-18 17:53:36.047573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf12c5dae04'
down_revision: Union[str, Sequence[str], None] = '2fe2f3c20576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('chunks', sa.Column('chunk_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('chunks_asset_uuid_key'), 'chunks', type_='unique')
    op.create_unique_constraint(None, 'chunks', ['chunk_uuid'])
    op.drop_column('chunks', 'asset_uuid')
    op.drop_column('chunks', 'asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('asset_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('chunks', sa.Column('asset_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunks', type_='unique')
    op.create_unique_constraint(op.f('chunks_asset_uuid_key'), 'chunks', ['asset_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('chunks', 'chunk_uuid')
    op.drop_column('chunks', 'chunk_id')
    # ### end Alembic commands ###
