name: Deploy Main Branch to Server

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with: 
          host: ${{ secrets.SSH_MAIN_HOST_IP }}
          username: github_user
          key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }}
          script: |
            cd /home/github_user/workspace/mini-rag
            git checkout main
            git pull
            sudo systemctl restart minirag.service
            echo "Deployment to main branch completed successfully!"
            sleep 10

            for i in {1..6}; do
              if ss -tuln | grep -q ':80'; then
                echo "✅ Port 80 is open, server is up and running."
                break
              else
                echo "⏳ Waiting for server to start..."
                sleep 5
              fi
              done

              if ! ss -tuln | grep -q ':80'; then
                echo "❌ Service failed to start on port 80."
                exit 1
              fi

              